### ISSUE TITLE
When will the code be open-souced?

### ISSUE THREAD

**Issue by zezhongding** [armingerami/GUST-Graph-Edge-Coloring-Utilization-to-Accelerate-Sparse-Matrix-Vector-Multiplication#1]
I have finished reading your article and am very interested in your work. Could you please let me know when the related code will be open-sourced? Thank you!

**Comment by armingerami** [comment]
Hi Ding, thank you for your interest. I've updated the repo. Let me know if you have any questions.

**Comment by zezhongding** [comment]
Thank you very much! I have no questions.
